USE TASK3; 
CREATE TABLE DEPARTMENTS (
ID INT PRIMARY KEY,
DEPARTMENT_NAME TEXT,
LOCATION TEXT
);
INSERT INTO DEPARTMENTS (ID, DEPARTMENT_NAME, LOCATION) VALUES
(1, 'FINANCE', 'NEWYORK'),
(2, 'HR', 'SAN FRANCISCO'),
(3, 'IT', 'NEW YORK'),
(4, 'MARKETING', 'CHICAGO');
SELECT * FROM DEPARTMENTS;
ALTER TABLE DEPARTMENTS
RENAME COLUMN ID TO DEPARTMENT_ID;
CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT PRIMARY KEY,
NAME VARCHAR(100),
DEPARTMENT_ID INT,
SALARY DECIMAL(10,2),
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);
ALTER TABLE EMPLOYEES
MODIFY COLUMN NAME VARCHAR(100);
INSERT INTO EMPLOYEES ( EMPLOYEE_ID, NAME, DEPARTMENT_ID, SALARY) VALUES
(101, 'ALEX', 1, 75000),
(102, 'JULIE', 2, 62000),
(103, 'BOBBIE', 3, 70000),
(104, 'DIANA', 4, 68000),
(105, 'EDWARD', 1, 77000);
SELECT NAME 
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE LOCATION = 'NEWYORK'
);

SELECT NAME 
FROM EMPLOYEES E 
WHERE EXISTS ( 
SELECT 1
FROM DEPARTMENTS D
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
AND LOCATION = 'NEWYORK'
);
SELECT NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'FINANCE'
);