USE TASK3;
CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT PRIMARY KEY,
NAME VARCHAR(100),
EMAIL VARCHAR(100),
CITY VARCHAR(50)
);
INSERT INTO CUSTOMERS ( CUSTOMER_ID, NAME, EMAIL, CITY) VALUES
(1, 'ALEX', NULL, 'TIRUPATI'),
(2, 'ALI', NULL, 'NELLORE'),
(3, 'JULIE', NULL, 'CHITTOOR'),
(4, 'FT', NULL, 'KURNOOL');
CREATE TABLE ORDERS (
ORDER_ID INT ,
CUSTOMER_ID INT,
ORDER_DATE DATE,
TOTAL_AMOUNT DECIMAL(10,2)
); 
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES
(1, 1, '2025-07-03', '4000.00'),
(2, 2, '2025-07-03', '5000.00'),
(3, 3, '2025-07-03', '4000.00'),
(4, 1, '2025-07-03', '4000.00'),
(5, 2, '2025-07-03', '4000.00'),
(6, 3, '2025-07-03', '4000.00');

SELECT C.CUSTOMER_ID, C.NAME, C.CITY,
COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM
CUSTOMERS C 
JOIN 
ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY 
C.CUSTOMER_ID, C.NAME, C.CITY
HAVING 
SUM(O.TOTAL_AMOUNT) > 5000;

CREATE VIEW FAVOURITECUSTOMERS AS
SELECT
C.CUSTOMER_ID, C.NAME, C.CITY,
COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
SUM(TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C 
JOIN 
ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID 
GROUP BY
C.CUSTOMER_ID, C.NAME, C.CITY
HAVING
SUM(O.TOTAL_AMOUNT) > 5000;
SELECT NAME, CITY, TOTAL_SPENT FROM FAVOURITECUSTOMERS; 
